import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import StoreProvider from "./redux/StoreProvider";
import InitUser from "./InitUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="
      bg-linear-to-b from-green-100 to-white min-h-screen w-full"
        
      >
        <Provider>
          <StoreProvider>
            <InitUser/>
            {children}
            
          </StoreProvider>
        
        </Provider>
      </body>
    </html>
  );
}
